server:
  port: 9110
  servlet:
    context-path: /push

spring:
  application:
    name: PUSH-SERVICE
  config:
    import:
      - optional:configserver:https://setlog.net/trading-config-server/
      - optional:classpath:telegram.yml
  zipkin:
    base-url: http://setlog.net:9411/
  sleuth:
    sampler:
      probability: 1.0
