server:
  port: 9110
  servlet:
    context-path: /push

spring:
  profiles:
    default: local
  application:
    name: PUSH-SERVICE
  config:
    import:
      - optional:configserver:https://centos-blog/trading-config-server/
      - optional:classpath:telegram.yml
      - optional:classpath:mongodb.yml
  zipkin:
    base-url: http://centos-blog:9411/
  sleuth:
    sampler:
      probability: 1.0
